import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

export const HERE = dirname(fileURLToPath(import.meta.url));
export const REPO_ROOT = resolve(HERE, "../..");
export const TD_PATH = resolve(REPO_ROOT, "docs/models/live-ipc.td");
export const OUT_RUST = resolve(
  REPO_ROOT,
  "crates/deslop-core/src/wire_generated.rs",
);
export const OUT_TS = resolve(
  REPO_ROOT,
  "clients/vscode/src/types/wire-generated.ts",
);

// External TypeScript types (defined in clients/vscode/src/types/report.ts)
// re-imported by the generated TS file when referenced. Skipped
// automatically when the type is defined in TYPE_CONFIG.
export const EXTERNAL_TS_TYPES = {
  ReportCluster: "./report",
  EmbeddingProvenance: "./report",
  CacheStats: "./report",
};

// Maps an external Rust type name (referenced from the .td but not
// defined in it) to the `use` path the post-processor must inject.
// Imports are emitted only when the generated code actually references
// the type so `unused_imports` warnings stay quiet.
export const EXTERNAL_TYPES = {
  ReportCluster: "crate::report::ReportCluster",
  EmbeddingProvenance: "crate::report::EmbeddingProvenance",
  CacheStats: "crate::report::CacheStats",
};

export const HEADER_PRELUDE = `//! Generated wire-format models for the Deslop live IPC surface.
//!
//! Source: \`docs/models/live-ipc.td\` (typeDiagram).
//! Generator: \`scripts/typediagram/generate.mjs\`.
//!
//! DO NOT EDIT BY HAND. Re-run \`make typediagram-gen\` (or any cargo
//! build) to regenerate. This file is gitignored.

use std::path::PathBuf;

use serde::{Deserialize, Serialize};
`;

export const TS_HEADER = `// @generated by scripts/typediagram/generate.mjs from docs/models/live-ipc.td
// DO NOT EDIT BY HAND. Re-run \`make typediagram-gen\` to regenerate.
// Per CLAUDE.md the generated wire types are gitignored; the .td file is
// the single source of truth for shapes shared with the Rust transports.
`;
