# agent-pmo:f87d349
[defaults]
exclude = [
  "**/.deslop/**",
  "**/.vscode-test/**",
  "**/__generated__/**",
  "**/bin/**",
  "**/coverage/**",
  "**/dist/**",
  "**/generated/**",
  "**/media/webview/**",
  "**/node_modules/**",
  "**/obj/**",
  "**/out/**",
  "**/target/**",
  "**/test/fixtures/**",
  "**/tests/fixtures/**",
  "**/*.designer.cs",
  "**/*.g.cs",
  "**/*.generated.cs",
  "**/*.openapi.cs",
  "**/*.pb.cs",
  "**/_site/**",
  "**/scripts/**",
  "**/eleventy.config.js",
  # in soure control we comment this line out so users can see the examples
  # when calculating the percentage, we must ignore the examples
  "examples/**",
]

[threshold]
max_duplication_percent = 9.9
