// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint

int sumRange(int lo, int hi) {
  var total = 0;
  for (var value = lo; value <= hi; value = value + 1) {
    total = total + value;
  }
  return total;
}
