//! Regression coverage for #165 [EXCLUSION-CONFIG]: Flutter/Dart
//! machine-generated files (generated localizations, etc.) carry the
//! banner "This file has been automatically generated. Please do not edit
//! it manually." The generated-header detector matched `auto generated` /
//! `autogenerated` but not the phrase "automatically generated", so these
//! files were not hidden and dominated the worst-offenders ranking on a
//! stock Flutter analysis. A file carrying this banner must be hidden from
//! the ranked report.

use std::{
    fs,
    path::{Path, PathBuf},
};

use anyhow::Result;
use assert_cmd::Command;
use serde_json::Value;

fn report_path(tmp: &Path) -> PathBuf {
    let mut path = tmp.join("report");
    let _replaced = path.set_extension("json");
    path
}

fn clusters(report: &Value) -> &[Value] {
    report
        .get("clusters")
        .and_then(Value::as_array)
        .map(Vec::as_slice)
        .unwrap_or_default()
}

fn cluster_spans(cluster: &Value, left: &str, right: &str) -> bool {
    let paths: Vec<&str> = cluster
        .get("occurrences")
        .and_then(Value::as_array)
        .map(Vec::as_slice)
        .unwrap_or_default()
        .iter()
        .filter_map(|occ| occ.get("path").and_then(Value::as_str))
        .collect();
    paths.iter().any(|path| path.ends_with(left))
        && paths.iter().any(|path| path.ends_with(right))
}

#[test]
fn dart_automatically_generated_banner_is_hidden() -> Result<()> {
    let tmp = tempfile::tempdir()?;
    let src = tmp.path().join("src");
    fs::create_dir(&src)?;

    // The Flutter framework banner verbatim, followed by a non-trivial
    // duplicated function body so a genuine clone cluster would surface
    // were the header not recognised.
    let header = "// This file has been automatically generated. \
        Please do not edit it manually.\n";
    let body = "String formatLabel(int value) {\n  \
        final doubled = value * 2;\n  \
        final label = 'item-$doubled';\n  \
        return label.toUpperCase();\n}\n";
    let file = format!("{header}{body}");
    fs::write(src.join("messages_en.dart"), &file)?;
    fs::write(src.join("messages_fr.dart"), &file)?;

    let report = report_path(tmp.path());
    let mut cmd = Command::cargo_bin("deslop")?;
    let _assertion = cmd
        .arg(&src)
        .arg("--min-nodes")
        .arg("5")
        .arg("--embeddings")
        .arg("off")
        .arg("--notext")
        .arg("--nohtml")
        .arg("--output")
        .arg(tmp.path().join("report"))
        .assert()
        .success();

    let body = fs::read_to_string(&report)?;
    let json: Value = serde_json::from_str(&body)?;
    let leaked = clusters(&json)
        .iter()
        .any(|cluster| cluster_spans(cluster, "messages_en.dart", "messages_fr.dart"));
    assert!(
        !leaked,
        "files carrying the 'automatically generated' banner must be hidden \
         from the ranked report: {body}"
    );
    Ok(())
}
