#!/usr/bin/env python3
"""[CORPUS-SCORE] Report one-cluster extent for the pinned Axios range repro."""

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
REPORTS = ROOT / ".corpus/version-compare/reports"
OUTPUT = REPORTS / "RANGE-COVERAGE.md"
BASELINE_SHA = "f92300e5e1004ef6c53a94174a0d7e842232ec80"
FIX_SHA = "8e09786a7e702935b4d551c7f641a162620080c8"
TARGETS = (
    ("test/module/typings/cjs/index.ts", 129, 212),
    ("test/module/typings/esm/index.ts", 152, 235),
)
INTRO = "The target is the complete copied block: `cjs/index.ts:129–212` and `esm/index.ts:152–235`. Each cell counts lines covered by the **single identical cluster** that covers the most of both ranges. The spans are that cluster's actual reported occurrences."
SCOPE = "This full-block diagnostic is separate from the [judged-range scorecard](SCORE.md#judged-range-coverage). The register judges a shorter Axios range, which both versions cover in full; that narrower target cannot show whether the entire copied block appears as one cluster."
PROVENANCE = "Generated by `python3 scripts/corpus/report-range-extent.py` from the archived comparison's `meta.json` and raw JSON reports."


def overlap(occurrence, target):
    """Count the judged lines inside one visible occurrence."""
    start = max(occurrence["start_line"], target[1])
    end = min(occurrence["end_line"], target[2])
    return max(0, end - start + 1)


def best_occurrence(cluster, target):
    """Find this cluster's widest visible occurrence on a target file."""
    options = (
        occurrence
        for occurrence in cluster["occurrences"]
        if occurrence["path"] == target[0] and not occurrence.get("hidden", False)
    )
    return max(options, key=lambda occurrence: overlap(occurrence, target), default=None)


def cluster_measurement(cluster):
    """Require the same identical cluster to cover both target files."""
    labels = [cluster[field] for field in ("kind", "bucket") if field in cluster]
    if not labels or any(label != "identical" for label in labels):
        return None
    occurrences = tuple(best_occurrence(cluster, target) for target in TARGETS)
    if any(occurrence is None for occurrence in occurrences):
        return None
    covered = tuple(overlap(occurrence, target) for occurrence, target in zip(occurrences, TARGETS))
    if any(lines == 0 for lines in covered):
        return None
    return cluster["id"], occurrences, covered


def best_measurement(report):
    """Choose the single cluster covering the most judged lines in both files."""
    measurements = (cluster_measurement(cluster) for cluster in report["clusters"])
    candidates = (measurement for measurement in measurements if measurement is not None)
    return max(candidates, key=lambda measurement: (sum(measurement[2]), measurement[0]))


def report_row(label, report_path):
    """Render measured counts and the source spans, retaining raw-report provenance."""
    report = json.loads(report_path.read_text())
    cluster_id, occurrences, covered = best_measurement(report)
    counts = [f"{lines}/{target[2] - target[1] + 1}" for lines, target in zip(covered, TARGETS)]
    spans = [f"{occurrence['start_line']}–{occurrence['end_line']}" for occurrence in occurrences]
    source = report_path.relative_to(REPORTS)
    return f"| {label} | {' + '.join(counts)} | {' + '.join(spans)} | [`{cluster_id}`]({source}) |"


def render_report(axios, rows):
    """Format the separately measured extent beside its provenance."""
    return "\n".join([
        "# Axios full-block range coverage",
        "",
        f"Target: Axios `{axios['sha']}`. Compared Deslop `{BASELINE_SHA}` with `{FIX_SHA}`.",
        "",
        INTRO,
        "",
        "| engine | CJS + ESM covered lines | reported CJS + ESM spans | cluster in raw report |",
        "|---|---|---|---|",
        *rows,
        "",
        SCOPE,
        "",
        PROVENANCE,
        "",
    ])


def main():
    """Read the exact two archived engine reports and write their range comparison."""
    meta = json.loads((REPORTS / "meta.json").read_text())
    if (meta["deslop"]["a"]["sha"], meta["deslop"]["b"]["sha"]) != (BASELINE_SHA, FIX_SHA):
        raise ValueError("archived comparison is not v0.32.0 versus the pushed fix")
    axios = next(target for target in meta["targets"] if target["slug"] == "axios")
    rows = [report_row(label, Path(axios["reports"][engine])) for label, engine in (("v0.32.0", "a"), ("pushed fix", "b"))]
    OUTPUT.write_text(render_report(axios, rows))


if __name__ == "__main__":
    main()
