// Three unrelated Rust scenarios: generated-module documentation, and
// the optional-versus-required pointer semantics of an empty record.
// Different inputs, different outputs, different behaviour.

test("documents the generated Rust module", () => {
  const schema = loadFixture("documented-records.td");
  const generated = generateRust(schema, { tdbin: true });
  expect(generated).toContain("//! Generated by typediagram. Do not edit.");
  expect(generated).toContain("/// A customer of the billing system.");
  expect(generated).toContain("pub struct Customer {");
});

test("points an optional empty record at the null offset", () => {
  const schema = loadFixture("empty-record-optional.td");
  const generated = generateRust(schema, { tdbin: true });
  expect(generated).toContain("pub marker: Option<EmptyMarker>");
  expect(generated).toContain("const EMPTY_MARKER_OFFSET: usize = 0;");
});

test("points a required empty record at the shared singleton", () => {
  const schema = loadFixture("empty-record-required.td");
  const generated = generateRust(schema, { tdbin: true });
  expect(generated).toContain("pub marker: EmptyMarker");
  expect(generated).toContain("const EMPTY_MARKER_SINGLETON: EmptyMarker = EmptyMarker;");
});
