//! [EXCLUSION-GENERATED-BANNER] Every language plugin says what a comment
//! is in its own grammar ([PIPELINE-LANG-TRAIT]), so a banner is found
//! whatever comment syntax carries it: `//`, `#`, `/* */`, a `/** */`
//! block with a ` * ` gutter, F#'s `(* *)`, under PHP's `<?php` tag,
//! behind a byte-order mark, and with Windows line endings.
//!
//! Each language gets two hand-written copies of one function and one
//! generated copy. The hand-written pair keeps the cluster in the report,
//! so the generated copy's occurrence is there to be read: hidden, with
//! none of its lines in the percentage.

use std::{fs, path::Path};

use anyhow::{anyhow, Result};
use serde_json::Value;

use super::{assert_visibility, scan};
use crate::common::{scan_dir::temp_scan_dir, *};

/// The scan root inside the temp workspace.
const SCAN_DIR: &str = "src";

/// File stems: two hand-written copies and the generator's output.
const HAND_WRITTEN_STEMS: [&str; 2] = ["plain_a", "plain_b"];
const GENERATED_STEM: &str = "generated";

/// A docstring is a string, not a comment, so a banner inside one never
/// counts — the file below is as visible as its hand-written siblings.
const DOCSTRING_STEM: &str = "docstring_only";
const PYTHON_EXTENSION: &str = "py";
const PYTHON_DOCSTRING_BANNER: &str =
    "\"\"\"Generated by the protocol buffer compiler.  DO NOT EDIT!\"\"\"\n\n";

/// One language's corner of the corpus.
struct Language {
    /// File extension, which also selects the plugin.
    extension: &'static str,
    /// What every file of the language opens with, before any comment.
    prologue: &'static str,
    /// The generator's banner in the language's own comment syntax.
    banner: &'static str,
    /// The function all three files hold, copied verbatim.
    function: &'static str,
}

const LANGUAGES: [Language; 10] = [
    Language {
        extension: "dart",
        prologue: "",
        banner: "// GENERATED CODE - DO NOT MODIFY BY HAND\n\n",
        function: "String describeTotal(int count) {\n  final doubled = count * 2;\n  \
                   final label = 'total-$doubled';\n  return label.toLowerCase();\n}\n",
    },
    Language {
        extension: PYTHON_EXTENSION,
        prologue: "",
        banner: "# -*- coding: utf-8 -*-\n\
                 # Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!\n\n",
        function: "def describe_total(count):\n    doubled = count * 2\n    \
                   label = 'total-' + str(doubled)\n    return label.lower()\n",
    },
    Language {
        extension: "go",
        prologue: "",
        banner: "// Code generated by protoc-gen-go. DO NOT EDIT.\n// versions:\n\
                 // \tprotoc-gen-go v1.31.0\n\n",
        function: "package sample\n\nfunc describeTotal(count int) string {\n\tdoubled := count * 2\n\t\
                   label := fmt.Sprintf(\"total-%d\", doubled)\n\treturn strings.ToLower(label)\n}\n",
    },
    // A byte-order mark and Windows line endings, as Visual Studio writes
    // a designer file.
    Language {
        extension: "cs",
        prologue: "\u{feff}",
        banner: "//------------------------------------------------------------------------------\r\n\
                 // <auto-generated>\r\n//     This code was generated by a tool.\r\n\
                 // </auto-generated>\r\n\
                 //------------------------------------------------------------------------------\r\n\r\n",
        function: "namespace Sample\r\n{\r\n    public static class Totals\r\n    {\r\n        \
                   public static string DescribeTotal(int count)\r\n        {\r\n            \
                   var doubled = count * 2;\r\n            var label = \"total-\" + doubled;\r\n            \
                   return label.ToLowerInvariant();\r\n        }\r\n    }\r\n}\r\n",
    },
    // A documentation block with a ` * ` gutter, under two lint pragmas.
    Language {
        extension: "ts",
        prologue: "",
        banner: "/* tslint:disable */\n/* eslint-disable */\n/**\n * Totals API\n *\n \
                 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).\n \
                 * Do not edit the class manually.\n */\n\n",
        function: "export function describeTotal(count: number): string {\n  const doubled = count * 2;\n  \
                   const label = `total-${doubled}`;\n  return label.toLowerCase();\n}\n",
    },
    Language {
        extension: "tsx",
        prologue: "",
        banner: "/**\n * @generated SignedSource<<0123456789abcdef0123456789abcdef>>\n */\n\n",
        function: "export function pickLabel(flags: string[]): string {\n  if (flags.length === 0) {\n    \
                   return 'none';\n  }\n  const first = flags[0];\n  return first.trim();\n}\n",
    },
    Language {
        extension: "js",
        prologue: "",
        banner: "// @generated by protoc-gen-es v1.10.0 with parameter \"target=js\"\n\
                 // @generated from file totals.proto (package sample, syntax proto3)\n\n",
        function: "export function sumRange(lo, hi) {\n  let total = 0;\n  \
                   for (let value = lo; value <= hi; value += 1) {\n    total += value;\n  }\n  \
                   return total;\n}\n",
    },
    Language {
        extension: "rs",
        prologue: "",
        banner: "/* automatically generated by rust-bindgen 0.69.4 */\n\n",
        function: "pub fn describe_total(count: i64) -> String {\n    let doubled = count * 2;\n    \
                   let label = format!(\"total-{doubled}\");\n    label.to_lowercase()\n}\n",
    },
    // PHP cannot open with a comment: the tag comes first.
    Language {
        extension: "php",
        prologue: "<?php\n",
        banner: "# Generated by the protocol buffer compiler.  DO NOT EDIT!\n# source: totals.proto\n\n",
        function: "function describeTotal(int $count): string\n{\n    $doubled = $count * 2;\n    \
                   $label = 'total-' . $doubled;\n    return strtolower($label);\n}\n",
    },
    Language {
        extension: "fs",
        prologue: "",
        banner: "(* @generated by totals-gen 3.1 *)\n",
        function: "module Totals\n\nlet describeTotal (count: int) : string =\n    \
                   let doubled = count * 2\n    let label = sprintf \"total-%d\" doubled\n    \
                   label.ToLowerInvariant()\n",
    },
];

impl Language {
    /// `<stem>.<extension>`.
    fn file(&self, stem: &str) -> String {
        format!("{stem}.{}", self.extension)
    }

    /// Writes the hand-written pair and the generated copy into `src`.
    fn write(&self, src: &Path) -> Result<()> {
        let plain = format!("{}{}", self.prologue, self.function);
        for stem in HAND_WRITTEN_STEMS {
            fs::write(src.join(self.file(stem)), &plain)?;
        }
        let generated = format!("{}{}{}", self.prologue, self.banner, self.function);
        Ok(fs::write(src.join(self.file(GENERATED_STEM)), generated)?)
    }

    /// Asserts the language's cluster shows the hand-written pair and
    /// hides the generated copy, in the rows and in the percentage.
    fn assert_only_generated_is_hidden(&self, report: &Value) -> Result<()> {
        let shown: Vec<String> = HAND_WRITTEN_STEMS.map(|stem| self.file(stem)).to_vec();
        let names: Vec<&str> = shown.iter().map(String::as_str).collect();
        let cluster = expect_cluster_spanning(report, &names)?;
        for name in names {
            assert_visibility(report, cluster, name, false)?;
        }
        assert_visibility(report, cluster, &self.file(GENERATED_STEM), true)
    }
}

#[test]
fn a_banner_is_found_in_every_language_s_comment_syntax() -> Result<()> {
    let (tmp, src) = temp_scan_dir(SCAN_DIR)?;
    LANGUAGES
        .iter()
        .try_for_each(|language| language.write(&src))?;

    let (report, _body) = scan(tmp.path(), &src)?;
    LANGUAGES
        .iter()
        .try_for_each(|language| language.assert_only_generated_is_hidden(&report))
}

#[test]
fn a_banner_inside_a_docstring_is_a_string_not_a_comment() -> Result<()> {
    let (tmp, src) = temp_scan_dir(SCAN_DIR)?;
    let python = LANGUAGES
        .iter()
        .find(|language| language.extension == PYTHON_EXTENSION)
        .ok_or_else(|| anyhow!("the corpus has a Python corner"))?;
    python.write(&src)?;
    let docstring_file = python.file(DOCSTRING_STEM);
    let source = format!("{PYTHON_DOCSTRING_BANNER}{}", python.function);
    fs::write(src.join(&docstring_file), source)?;

    let (report, _body) = scan(tmp.path(), &src)?;
    python.assert_only_generated_is_hidden(&report)?;
    let cluster = expect_cluster_spanning(&report, &[docstring_file.as_str()])?;
    assert_visibility(&report, cluster, &docstring_file, false)
}
