//! [EXCLUSION-GENERATED-BANNER] Every registered banner hides its file,
//! and a near miss never does.
//!
//! One Dart corpus in which every file holds the same function, so the
//! report carries one cluster whose occurrences say, file by file, which
//! were hidden — and the per-file metrics say whether their lines counted.

use std::{fs, path::Path};

use anyhow::Result;
use serde_json::Value;

use super::{assert_visibility, scan};
use crate::common::{scan_dir::temp_scan_dir, *};

/// The scan root inside the temp workspace.
const SCAN_DIR: &str = "src";

/// The function every file of the corpus holds, copied verbatim.
const SHARED_FUNCTION: &str = "String describeBasket(int count) {\n  \
     final doubled = count * 2;\n  \
     final label = 'basket-$doubled';\n  \
     return label.toUpperCase();\n}\n";

/// Report fields the cluster-level counts are read from.
const OCCURRENCES_TOTAL: &str = "occurrences_total";
const OCCURRENCE_COUNT: &str = "occurrence_count";
const DUPLICATED_LOC: &str = "duplicated_loc";

/// One file of the corpus: `before`, the shared function, then `after`.
struct Case {
    /// File name, which also names the case in a failure message.
    file: &'static str,
    /// What the file opens with.
    before: &'static str,
    /// What follows the shared function.
    after: &'static str,
}

impl Case {
    /// A file that opens with `before`, then holds the shared function.
    const fn opening(file: &'static str, before: &'static str) -> Self {
        Self {
            file,
            before,
            after: "",
        }
    }

    /// A file that holds the shared function, then `after`.
    const fn closing(file: &'static str, after: &'static str) -> Self {
        Self {
            file,
            before: "",
            after,
        }
    }
}

/// Generator output: each opens the way its generator really writes it.
const GENERATED: [Case; 14] = [
    Case::opening(
        "build_runner_output.dart",
        "// GENERATED CODE - DO NOT MODIFY BY HAND\n\n",
    ),
    Case::opening(
        "ffigen_output.dart",
        "// AUTO GENERATED FILE, DO NOT EDIT.\n//\n// Generated by `package:ffigen`.\n",
    ),
    Case::opening(
        "jnigen_output.dart",
        "// Autogenerated by jnigen. DO NOT EDIT!\n\n",
    ),
    Case::opening(
        "jnigen_versioned_output.dart",
        "// AUTO GENERATED BY JNIGEN 0.14.2. DO NOT EDIT!\n\n",
    ),
    Case::opening(
        "openapi_client.dart",
        "//\n// AUTO-GENERATED FILE, DO NOT MODIFY!\n//\n",
    ),
    // The banner sits under a licence block, after a blank line: every
    // opening comment is read, not only the first line.
    Case::opening(
        "flutter_localizations.dart",
        "// Copyright 2014 The Flutter Authors. All rights reserved.\n\
                 // Use of this source code is governed by a BSD-style license.\n\n\
                 // This file has been automatically generated. Please do not edit it manually.\n\
                 // To regenerate the file, use:\n\
                 // dart dev/tools/localization/bin/gen_localizations.dart --overwrite\n\n",
    ),
    Case::opening(
        "intl_messages.dart",
        "// DO NOT EDIT. This is code generated via package:intl/generate_localized.dart\n\
                 // This is a library that provides messages for a en locale.\n\n",
    ),
    Case::opening(
        "protoc_legacy.dart",
        "//\n//  Generated code. Do not modify.\n//  source: basket.proto\n//\n",
    ),
    Case::opening(
        "protoc_current.dart",
        "// This is a generated file - do not edit.\n//\n// Generated from basket.proto.\n\n",
    ),
    Case::opening(
        "pigeon_channel.dart",
        "// Autogenerated from Pigeon (v17.1.2), do not edit directly.\n\
                 // See also: https://pub.dev/packages/pigeon\n\n",
    ),
    // Banners are not tied to a language: a Go-style or protoc banner in
    // a Dart file's opening comment still declares the file generated.
    Case::opening(
        "go_convention.dart",
        "// Code generated by basket-gen v2. DO NOT EDIT.\n\n",
    ),
    Case::opening(
        "protoc_any_language.dart",
        "// Generated by the protocol buffer compiler.  DO NOT EDIT!\n// source: basket.proto\n\n",
    ),
    // A block comment, another letter case, and ragged spacing all fold
    // away.
    Case::opening(
        "block_comment_output.dart",
        "/*\n *   generated   code - do not modify by hand\n */\n",
    ),
    Case::opening("marker_only.dart", "/// @generated\n"),
];

/// Hand-written files. Each comes as close to a banner as prose can.
const HAND_WRITTEN: [Case; 9] = [
    Case::opening(
        "no_header.dart",
        "",
    ),
    // A sentence that contains a whole banner is still a sentence.
    Case::opening(
        "banner_inside_sentence.dart",
        "// Files under gen/ open with GENERATED CODE - DO NOT MODIFY BY HAND, this one does not.\n",
    ),
    // Starts like the Go convention, ends like prose.
    Case::opening(
        "half_a_frame.dart",
        "// Code generated by hand is still code, so review it like any other.\n",
    ),
    Case::opening(
        "marker_inside_sentence.dart",
        "// Files marked @generated are skipped by the formatter; this file is not one.\n",
    ),
    // A string is code, whatever it says.
    Case::opening(
        "banner_in_string.dart",
        "const banner = '// GENERATED CODE - DO NOT MODIFY BY HAND';\n\n",
    ),
    // Only the opening comments count: this one follows code.
    Case::opening(
        "banner_after_code.dart",
        "import 'dart:math';\n\n// GENERATED CODE - DO NOT MODIFY BY HAND\n",
    ),
    Case::closing(
        "banner_at_end.dart",
        "\n// GENERATED CODE - DO NOT MODIFY BY HAND\n",
    ),
    // A banner quoted as an example is a quotation: the marker in front
    // of it belongs to the prose, not to the file.
    Case::opening(
        "banner_quoted_as_example.dart",
        "// ffigen output opens with this line:\n//\n//     // AUTO GENERATED FILE, DO NOT EDIT.\n",
    ),
    // The banner's words split across two comment lines are two lines,
    // and neither is the banner.
    Case::opening(
        "banner_wrapped.dart",
        "// This file has been automatically generated. Please do not\n// edit it manually.\n",
    ),
];

/// Writes every case into `src`.
fn write_cases(src: &Path, cases: &[Case]) -> Result<()> {
    cases.iter().try_for_each(|case| {
        let source = format!("{}{SHARED_FUNCTION}{}", case.before, case.after);
        Ok(fs::write(src.join(case.file), source)?)
    })
}

/// Asserts every case's occurrence carries `hidden`.
fn assert_cases(report: &Value, cluster: &Value, cases: &[Case], hidden: bool) -> Result<()> {
    cases
        .iter()
        .try_for_each(|case| assert_visibility(report, cluster, case.file, hidden))
}

/// Reads one cluster-level count.
fn count(cluster: &Value, name: &str) -> Option<usize> {
    field(cluster, name)
        .as_u64()
        .and_then(|value| usize::try_from(value).ok())
}

#[test]
fn every_registered_banner_hides_its_file_and_a_near_miss_never_does() -> Result<()> {
    let (tmp, src) = temp_scan_dir(SCAN_DIR)?;
    write_cases(&src, &GENERATED)?;
    write_cases(&src, &HAND_WRITTEN)?;

    let (report, _body) = scan(tmp.path(), &src)?;
    let shown: Vec<&str> = HAND_WRITTEN.iter().map(|case| case.file).collect();
    let cluster = expect_cluster_spanning(&report, &shown)?;
    let everything = GENERATED.len().saturating_add(HAND_WRITTEN.len());
    assert_eq!(count(cluster, OCCURRENCES_TOTAL), Some(everything));
    assert_eq!(count(cluster, OCCURRENCE_COUNT), Some(HAND_WRITTEN.len()));
    assert_cases(&report, cluster, &GENERATED, true)?;
    assert_cases(&report, cluster, &HAND_WRITTEN, false)?;
    // One decision per file: the headline figure is exactly the lines the
    // shown occurrences cover, so rows and percentage cannot disagree.
    assert_eq!(
        metric_field(&report, DUPLICATED_LOC).as_u64(),
        Some(visible_duplicated_loc(&report)),
        "duplicated_loc must count the shown occurrences and nothing else: {report:#}"
    );
    Ok(())
}
