#!/usr/bin/env python3
"""Emit the dedup session report from the measurements that produced it.

Inputs are the artefacts of the runs themselves — a Deslop JSON metrics
blob and the before/after `cargo test` listings — so every figure in the
output is read from a file a run wrote, never typed in by hand.

Usage:
  dedup_session.py --before <metrics.json> --after <metrics.json> \
      --baseline <tests.txt> --final <tests.txt> --out <report.md>
"""
import argparse
import json
import pathlib

# A cargo listing line looks like: `test <name> ... ok`
PASS_SUFFIX = " ok"
TEST_PREFIX = "test "


def test_names(path, passing_only):
    """Test names in a `cargo test` listing, optionally only the passing."""
    names = set()
    for line in pathlib.Path(path).read_text().splitlines():
        if not line.startswith(TEST_PREFIX):
            continue
        if passing_only and not line.endswith(PASS_SUFFIX):
            continue
        names.add(line[len(TEST_PREFIX):].split(" ... ")[0])
    return names


def metrics(path):
    """The repo metrics block of a Deslop JSON report."""
    blob = json.loads(pathlib.Path(path).read_text())
    return blob.get("metrics", blob)


def row(label, before, after, fmt="{:,}"):
    delta = after - before
    sign = "+" if delta > 0 else ""
    return (
        f"| {label} | {fmt.format(before)} | {fmt.format(after)} "
        f"| {sign}{fmt.format(delta)} |"
    )


def main():
    parser = argparse.ArgumentParser()
    for flag in ("before", "after", "baseline", "final", "out"):
        parser.add_argument(f"--{flag}", required=True)
    args = parser.parse_args()

    start, end = metrics(args.before), metrics(args.after)
    base_all, final_all = test_names(args.baseline, False), test_names(args.final, False)
    base_ok, final_ok = test_names(args.baseline, True), test_names(args.final, True)

    regressed = sorted(base_ok - final_ok)
    lines = [
        "# Deduplication session — measured result",
        "",
        "Generated by `scripts/reports/dedup_session.py` from the Deslop",
        "report metrics and the `cargo test` listings of the runs themselves.",
        "",
        "## Duplication",
        "",
        "| Measure | Before | After | Change |",
        "| --- | ---: | ---: | ---: |",
        row("Duplicated LOC", start["duplicated_loc"], end["duplicated_loc"]),
        row("Clusters", start["clusters_total"], end["clusters_total"]),
        row("Analysed LOC", start["analysed_loc"], end["analysed_loc"]),
        row("Files with duplication", start["duplicated_files"], end["duplicated_files"]),
        row(
            "Duplication percent",
            start["duplication_percent"],
            end["duplication_percent"],
            "{:.4f}",
        ),
        "",
        "## Test differential (`cargo test -p deslop --test suite`)",
        "",
        "| Measure | Baseline | After | Change |",
        "| --- | ---: | ---: | ---: |",
        row("Tests present", len(base_all), len(final_all)),
        row("Tests passing", len(base_ok), len(final_ok)),
        "",
        f"Tests that passed at baseline and no longer pass: **{len(regressed)}**",
        "",
    ]
    lines += [f"- `{name}`" for name in regressed] or ["_None._"]
    lines += [
        "",
        "## Coverage of this verification",
        "",
        f"- {len(base_ok)} of {len(base_all)} tests execute their assertions; "
        "the rest abort inside the engine before reaching them.",
        "- A refactor of a non-executing test is compile-verified only. Its "
        "assertions cannot be observed until the engine runs again.",
        "",
    ]
    pathlib.Path(args.out).write_text("\n".join(lines) + "\n")
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
