#!/usr/bin/env python3
"""Break a Deslop JSON report into the categories that decide whether its
duplication can actually be removed.

Answers one question mechanically: of the duplicated lines Deslop reports
against this repository, how many sit in clusters large enough that a
helper could absorb them, and how many sit in fragments too small to
extract without deleting assertions?

Usage:  duplication_anatomy.py <report.json> <output.md>
"""

import json
import sys
from collections import defaultdict
from pathlib import Path

# A cluster must clear this many canonical AST nodes before a helper can
# absorb it without the helper costing more lines than it saves. Roughly
# 30 lines of Rust.
EXTRACTABLE_NODE_FLOOR = 90

# Node count below which an occurrence is a mandatory language idiom --
# a constructor call plus a couple of bindings -- with nothing to hoist.
IDIOM_NODE_CEILING = 40


def load(path):
    with open(path, encoding="utf-8") as handle:
        return json.load(handle)


def is_test_path(path):
    return "/tests/" in path or path.endswith("tests.rs") or ".test." in path


def main():
    if len(sys.argv) != 3:
        print(__doc__)
        return 2
    report = load(sys.argv[1])
    clusters = report.get("clusters", [])
    metrics = report.get("metrics", {})

    by_band = defaultdict(lambda: {"clusters": 0, "occurrences": 0})
    test_clusters = production_clusters = 0
    extractable = idiom = middle = 0
    kinds = defaultdict(int)

    for cluster in clusters:
        nodes = cluster.get("canonical_node_count", 0)
        occurrences = cluster.get("occurrences", [])
        kinds[cluster.get("kind", "unknown")] += 1
        by_band[cluster.get("rank_band", "?")]["clusters"] += 1
        by_band[cluster.get("rank_band", "?")]["occurrences"] += len(occurrences)
        if all(is_test_path(o.get("path", "")) for o in occurrences):
            test_clusters += 1
        else:
            production_clusters += 1
        if nodes >= EXTRACTABLE_NODE_FLOOR:
            extractable += 1
        elif nodes <= IDIOM_NODE_CEILING:
            idiom += 1
        else:
            middle += 1

    total = len(clusters)

    def pct(part):
        return (100.0 * part / total) if total else 0.0

    lines = []
    add = lines.append
    add("# Duplication anatomy")
    add("")
    add(f"Generated by `scripts/reports/duplication_anatomy.py` from "
        f"`{Path(sys.argv[1]).name}`. Every number below is read out of that "
        f"report; none is hand-entered.")
    add("")
    add("## Headline")
    add("")
    add("| Figure | Value |")
    add("| --- | --- |")
    add(f"| Analysed LOC | {metrics.get('analysed_loc', 0)} |")
    add(f"| Duplicated LOC | {metrics.get('duplicated_loc', 0)} |")
    add(f"| Duplication percent | {metrics.get('duplication_percent', 0.0):.4f} |")
    add(f"| Visible clusters | {total} |")
    add(f"| Duplicated files | {metrics.get('duplicated_files', 0)} |")
    add("")
    add("## Can these clusters be merged?")
    add("")
    add(f"A helper only pays for itself above roughly {EXTRACTABLE_NODE_FLOOR} "
        f"canonical nodes (~30 lines). At or below {IDIOM_NODE_CEILING} nodes a "
        f"cluster is a mandatory idiom -- a constructor plus a binding or two, "
        f"or a run of distinct assertions -- with nothing to hoist.")
    add("")
    add("| Class | Clusters | Share |")
    add("| --- | ---: | ---: |")
    add(f"| Extractable (>= {EXTRACTABLE_NODE_FLOOR} nodes) | {extractable} | {pct(extractable):.1f}% |")
    add(f"| Middle ({IDIOM_NODE_CEILING + 1}-{EXTRACTABLE_NODE_FLOOR - 1} nodes) | {middle} | {pct(middle):.1f}% |")
    add(f"| Idiom (<= {IDIOM_NODE_CEILING} nodes) | {idiom} | {pct(idiom):.1f}% |")
    add("")
    add("## Where the clusters live")
    add("")
    add("| Location | Clusters | Share |")
    add("| --- | ---: | ---: |")
    add(f"| Test-only (every occurrence under a test path) | {test_clusters} | {pct(test_clusters):.1f}% |")
    add(f"| Touches production code | {production_clusters} | {pct(production_clusters):.1f}% |")
    add("")
    add("## Clone kinds")
    add("")
    add("| Kind | Clusters |")
    add("| --- | ---: |")
    for kind, count in sorted(kinds.items(), key=lambda row: -row[1]):
        add(f"| {kind} | {count} |")
    add("")
    add("## Severity bands")
    add("")
    add("| Band | Clusters | Occurrences |")
    add("| --- | ---: | ---: |")
    for band in ("worst", "top10", "mid", "faint"):
        row = by_band.get(band)
        if row:
            add(f"| {band} | {row['clusters']} | {row['occurrences']} |")
    add("")
    add("## Largest clusters")
    add("")
    add("| Nodes | Occurrences | Kind | First occurrence |")
    add("| ---: | ---: | --- | --- |")
    for cluster in sorted(clusters, key=lambda c: -c.get("canonical_node_count", 0))[:15]:
        occurrences = cluster.get("occurrences", [])
        first = occurrences[0].get("path", "?") if occurrences else "?"
        add(f"| {cluster.get('canonical_node_count', 0)} | {len(occurrences)} "
            f"| {cluster.get('kind', '?')} | `{first}` |")
    add("")

    Path(sys.argv[2]).write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {sys.argv[2]}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
