//! Generator banners ([EXCLUSION-GENERATED-BANNER]): the whole comment
//! lines a generator opens its output with, and the walk that looks for
//! one in a file's opening comments.
//!
//! A banner is matched as a whole line of a comment the grammar found,
//! never as a phrase and never in raw bytes: a hand-written header that
//! merely describes a generator must not hide the file, because a hidden
//! file loses its duplicates from the report and from
//! `duplication_percent` at once.

use tree_sitter::Node;

use crate::lang::LanguageParser;

/// One way a generator announces its output.
#[derive(Debug, Clone, Copy)]
enum Banner {
    /// The comment line is exactly this text.
    Line(&'static str),
    /// The comment line starts with the first text and ends with the
    /// second; the generator's name, version or source sits between.
    Framed(&'static str, &'static str),
}

/// Every banner a file is hidden for, lower-case with single spaces — the
/// form [`comment_line`] produces. [EXCLUSION-GENERATED-BANNER] lists
/// each with the generator that writes it; a banner is added there first.
const GENERATED_BANNERS: &[Banner] = &[
    Banner::Line("generated code - do not modify by hand"),
    Banner::Line("auto generated file, do not edit."),
    Banner::Line("autogenerated by jnigen. do not edit!"),
    Banner::Framed("auto generated by jnigen", "do not edit!"),
    Banner::Line("auto-generated file, do not modify!"),
    Banner::Line("this file has been automatically generated. please do not edit it manually."),
    Banner::Line("do not edit. this is code generated via package:intl/generate_localized.dart"),
    Banner::Line("generated code. do not modify."),
    Banner::Line("this is a generated file - do not edit."),
    Banner::Framed("autogenerated from pigeon", "do not edit directly."),
    Banner::Framed("code generated ", "do not edit."),
    Banner::Line("generated by the protocol buffer compiler. do not edit!"),
    Banner::Line("generated by the grpc python protocol compiler plugin. do not edit!"),
    Banner::Framed("<auto-generated", ">"),
    Banner::Framed("<autogenerated", ">"),
    Banner::Line("@generated"),
    Banner::Framed("@generated by ", ""),
    Banner::Framed("@generated from ", ""),
    Banner::Framed("@generated signedsource<<", ""),
    Banner::Line("this file is @generated by prost-build."),
    Banner::Framed("automatically generated by rust-bindgen", ""),
    Banner::Framed("note: this class is auto generated by ", ""),
];

/// Punctuation a comment marker is made of: `//`, `///`, `//!`, `#`,
/// `/*`, `/**`, a block's ` * ` gutter, F#'s `(*`.
const MARKER_PUNCTUATION: [char; 5] = ['/', '*', '#', '!', '('];

/// Terminators a block comment's last line may close with.
const BLOCK_TERMINATORS: [&str; 2] = ["*/", "*)"];

impl Banner {
    /// Whether `line`, already in [`comment_line`] form, is this banner.
    fn matches(self, line: &str) -> bool {
        match self {
            Self::Line(text) => line == text,
            Self::Framed(opens, closes) => {
                line.len() >= opens.len().saturating_add(closes.len())
                    && line.starts_with(opens)
                    && line.ends_with(closes)
            }
        }
    }
}

/// [EXCLUSION-GENERATED-BANNER] Whether the file rooted at `root` opens
/// with a generator's banner: one of its opening comments — the comment
/// nodes above the first code, after any prologue such as PHP's `<?php`
/// — holds a line that is a registered banner.
pub(crate) fn opens_with_generated_banner(
    root: Node<'_>,
    source: &[u8],
    parser: &dyn LanguageParser,
) -> bool {
    let mut cursor = root.walk();
    let found = root
        .children(&mut cursor)
        .skip_while(|node| parser.is_prologue_kind(node.kind()))
        .take_while(|node| parser.is_comment_kind(node.kind()))
        .any(|comment| declares_generated(comment, source));
    found
}

/// Whether any line of `comment` is a registered banner.
fn declares_generated(comment: Node<'_>, source: &[u8]) -> bool {
    comment.utf8_text(source).is_ok_and(|text| {
        text.lines()
            .map(comment_line)
            .any(|line| GENERATED_BANNERS.iter().any(|banner| banner.matches(&line)))
    })
}

/// One line of a comment as its author worded it: the comment marker and
/// block terminator removed, whitespace runs collapsed, ASCII lower-cased.
///
/// Only the line's own marker goes — one unbroken run of punctuation. A
/// second marker after it (`//     // AUTO GENERATED FILE…`) is a banner
/// quoted as an example, so it stays in the text and the line matches
/// nothing.
fn comment_line(raw: &str) -> String {
    let worded = raw
        .trim_start()
        .trim_start_matches(MARKER_PUNCTUATION)
        .trim();
    let unterminated = BLOCK_TERMINATORS
        .iter()
        .find_map(|terminator| worded.strip_suffix(terminator))
        .unwrap_or(worded);
    unterminated
        .split_whitespace()
        .collect::<Vec<_>>()
        .join(" ")
        .to_ascii_lowercase()
}
